var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/reset-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__81e33659._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_2b5f7250._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2ad63b88._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e82ee19._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__e7b3e671._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(public)_layout_tsx_fedd9c1f._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_reset-password_page_actions_71b3934e.js")
R.m(98414)
module.exports=R.m(98414).exports
