var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/privacy/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__bc278b4f._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_e293ee71._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2ad63b88._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e82ee19._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__e7b3e671._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(public)_layout_tsx_fedd9c1f._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_privacy_page_actions_2908562d.js")
R.m(33206)
module.exports=R.m(33206).exports
