import type { Activity } from "@/types";
import { d } from "./helpers";

// ===== Mock Activities (~100 activities) =====

export const mockActivities: Activity[] = [
  // Recent pending activities (February 2026)
  { id: "act-1", title: "Ligar para Jean Pierre - alinhar onboarding", type: "call", status: "pending", description: "Alinhar primeira entrega e processos de pedido", dueDate: d(2026,2,10), dueTime: "10:00", responsibleId: "user-5", responsibleName: "Fernanda Lima", clientId: "client-35", clientName: "Restaurante Paris Bistro SA", createdAt: d(2026,2,8) },
  { id: "act-2", title: "Reunião de kickoff - Hotel Montanha Resort", type: "meeting", status: "pending", description: "Apresentar equipe e cronograma de implantação", dueDate: d(2026,2,9), dueTime: "14:00", responsibleId: "user-7", responsibleName: "Carolina Santos", clientId: "client-29", clientName: "Hotel Montanha Resort SA", createdAt: d(2026,2,7) },
  { id: "act-3", title: "Enviar proposta revisada - Wine Bar Sommelier", type: "email", status: "pending", description: "Proposta com desconto especial para contrato anual", dueDate: d(2026,2,9), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-o04", opportunityTitle: "Bebidas importadas - Wine Bar Sommelier", createdAt: d(2026,2,8) },
  { id: "act-4", title: "Follow-up negociação - Rede Padarias Artesanais", type: "follow-up", status: "pending", description: "Retornar sobre prazo de pagamento", dueDate: d(2026,2,9), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-o05", opportunityTitle: "Laticinios especiais - Rede Padarias Artesanais", createdAt: d(2026,2,7) },
  { id: "act-5", title: "WhatsApp - confirmar contrato Green Food", type: "whatsapp", status: "pending", description: "Confirmar recebimento do contrato assinado", dueDate: d(2026,2,10), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-o06", opportunityTitle: "Embalagens sustentáveis - Green Food Delivery", createdAt: d(2026,2,8) },
  { id: "act-6", title: "Reunião presencial - Restaurante Gaúcho Pampa", type: "meeting", status: "pending", description: "Apresentação de catálogo de carnes", dueDate: d(2026,2,9), dueTime: "15:00", responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-o09", opportunityTitle: "Carnes - Restaurante Gaúcho Pampa", createdAt: d(2026,2,6) },
  { id: "act-7", title: "Ligar para renovação - Delivery Gourmet", type: "call", status: "overdue", description: "Contrato vence em março, iniciar renovação", dueDate: d(2026,2,5), dueTime: "11:00", responsibleId: "user-5", responsibleName: "Fernanda Lima", clientId: "client-3", clientName: "Delivery Gourmet ME", createdAt: d(2026,2,1) },
  { id: "act-8", title: "Visita técnica - Hospital Santa Cruz", type: "visit", status: "pending", description: "Avaliar cozinha para otimização de entregas", dueDate: d(2026,2,12), dueTime: "09:00", responsibleId: "user-7", responsibleName: "Carolina Santos", clientId: "client-16", clientName: "Hospital Santa Cruz", createdAt: d(2026,2,6) },
  { id: "act-9", title: "Enviar catalogo atualizado - Beach Club Maré Alta", type: "email", status: "pending", description: "Catálogo de bebidas para temporada", dueDate: d(2026,2,11), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-o10", opportunityTitle: "Bebidas - Beach Club Maré Alta", createdAt: d(2026,2,8) },
  { id: "act-10", title: "Task - preparar licitação Hospital Regional", type: "task", status: "pending", description: "Reunir documentos para processo licitatório", dueDate: d(2026,2,15), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-o07", opportunityTitle: "Insumos gerais - Hospital Regional Norte", createdAt: d(2026,2,7) },
  // Overdue activities
  { id: "act-11", title: "Follow-up pos-venda - Restaurante Verde Vida", type: "follow-up", status: "overdue", description: "Cliente com health score crítico", dueDate: d(2026,1,28), responsibleId: "user-5", responsibleName: "Fernanda Lima", clientId: "client-8", clientName: "Restaurante Verde Vida ME", createdAt: d(2026,1,20) },
  { id: "act-12", title: "Ligar - Clube Recreativo Central", type: "call", status: "overdue", description: "Verificar satisfação e renovação", dueDate: d(2026,2,1), dueTime: "14:00", responsibleId: "user-7", responsibleName: "Carolina Santos", clientId: "client-18", clientName: "Clube Recreativo Central", createdAt: d(2026,1,25) },
  // Completed activities (recent - February 2026)
  { id: "act-13", title: "Reunião de fechamento - Paris Bistro", type: "meeting", status: "completed", description: "Assinatura de contrato", dueDate: d(2026,2,7), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w35", opportunityTitle: "Carnes premium - Restaurante Paris Bistro", completedAt: d(2026,2,7), createdAt: d(2026,2,5) },
  { id: "act-14", title: "Enviar contrato - Spa Wellness", type: "email", status: "completed", description: "Contrato de fornecimento enviado", dueDate: d(2026,2,6), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w36", opportunityTitle: "Hortifruti premium - Spa Wellness Center", completedAt: d(2026,2,6), createdAt: d(2026,2,4) },
  { id: "act-15", title: "Ligar - Pub Dublin confirmação", type: "call", status: "completed", description: "Confirmar última entrega e satisfação", dueDate: d(2026,2,8), dueTime: "10:00", responsibleId: "user-6", responsibleName: "Marcos Pereira", clientId: "client-new3", clientName: "Pub Irlandês Dublin Ltda", completedAt: d(2026,2,8), createdAt: d(2026,2,6) },
  { id: "act-16", title: "WhatsApp - Dark Kitchen Central", type: "whatsapp", status: "completed", description: "Confirmar horário de entrega", dueDate: d(2026,2,7), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w39", opportunityTitle: "Embalagens - Dark Kitchen Central", completedAt: d(2026,2,7), createdAt: d(2026,2,5) },
  // Completed activities (January 2026)
  { id: "act-17", title: "Reunião negociação - Fazenda Velha", type: "meeting", status: "completed", description: "Negociação de contrato anual", dueDate: d(2026,1,18), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w28", clientId: "client-28", completedAt: d(2026,1,18), createdAt: d(2026,1,15) },
  { id: "act-18", title: "Proposta enviada - Hotel Montanha Resort", type: "email", status: "completed", description: "Proposta de fornecimento de proteínas", dueDate: d(2026,1,15), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w29", completedAt: d(2026,1,15), createdAt: d(2026,1,12) },
  { id: "act-19", title: "Follow-up - Açaí Beach", type: "follow-up", status: "completed", description: "Confirmar interesse após reunião", dueDate: d(2026,1,20), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w30", completedAt: d(2026,1,20), createdAt: d(2026,1,18) },
  { id: "act-20", title: "Ligar - Cervejaria Hop", type: "call", status: "completed", description: "Alinhar primeiro pedido", dueDate: d(2026,1,25), dueTime: "11:00", responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w31", completedAt: d(2026,1,25), createdAt: d(2026,1,22) },
  { id: "act-21", title: "Visita técnica - Cafeteria Grão", type: "visit", status: "completed", description: "Avaliar estrutura de armazenamento", dueDate: d(2026,1,26), responsibleId: "user-4", responsibleName: "Juliana Costa", clientId: "client-32", completedAt: d(2026,1,26), createdAt: d(2026,1,23) },
  { id: "act-22", title: "Reunião fechamento - Restaurante Habibi", type: "meeting", status: "completed", description: "Assinatura de contrato", dueDate: d(2026,1,28), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w33", completedAt: d(2026,1,28), createdAt: d(2026,1,25) },
  { id: "act-23", title: "Email confirmação - Tapioca Express", type: "email", status: "completed", description: "Enviar confirmação de primeiro pedido", dueDate: d(2026,1,30), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w34", completedAt: d(2026,1,30), createdAt: d(2026,1,28) },
  // Completed activities (December 2025)
  { id: "act-24", title: "Reunião kickoff - Resort Praia Azul", type: "meeting", status: "completed", description: "Início do projeto", dueDate: d(2025,12,18), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w21", clientId: "client-21", completedAt: d(2025,12,18), createdAt: d(2025,12,15) },
  { id: "act-25", title: "Degustação - Sushi Ya", type: "meeting", status: "completed", description: "Apresentação de produtos premium", dueDate: d(2025,12,19), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w22", clientId: "client-22", completedAt: d(2025,12,19), createdAt: d(2025,12,16) },
  { id: "act-26", title: "Follow-up proposta - Gelaterias Itália", type: "follow-up", status: "completed", description: "Retorno após proposta", dueDate: d(2025,12,18), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w23", completedAt: d(2025,12,18), createdAt: d(2025,12,15) },
  { id: "act-27", title: "Reunião comercial - Casa de Shows Arena", type: "meeting", status: "completed", description: "Negociação de volumes para eventos", dueDate: d(2025,12,20), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w24", clientId: "client-24", completedAt: d(2025,12,20), createdAt: d(2025,12,17) },
  { id: "act-28", title: "Ligar - Catering VIP confirmação", type: "call", status: "completed", description: "Confirmar detalhes do contrato", dueDate: d(2025,12,22), dueTime: "10:00", responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w25", clientId: "client-25", completedAt: d(2025,12,22), createdAt: d(2025,12,19) },
  { id: "act-29", title: "Visita - Restaurante Mineiro Raiz", type: "visit", status: "completed", description: "Conhecer operação do cliente", dueDate: d(2025,12,23), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w26", completedAt: d(2025,12,23), createdAt: d(2025,12,20) },
  { id: "act-30", title: "Fechamento - Churrascaria Gaúcha", type: "meeting", status: "completed", description: "Assinatura de contrato", dueDate: d(2025,12,26), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w27", clientId: "client-27", completedAt: d(2025,12,26), createdAt: d(2025,12,23) },
  // Completed activities (November 2025)
  { id: "act-31", title: "Reunião inicial - Executivo Prime", type: "meeting", status: "completed", dueDate: d(2025,11,15), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w14", completedAt: d(2025,11,15), createdAt: d(2025,11,12) },
  { id: "act-32", title: "Degustação - Buffet Casamento Real", type: "meeting", status: "completed", dueDate: d(2025,11,17), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w15", completedAt: d(2025,11,17), createdAt: d(2025,11,14) },
  { id: "act-33", title: "Reunião licitação - Hospital Santa Cruz", type: "meeting", status: "completed", dueDate: d(2025,11,18), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w16", completedAt: d(2025,11,18), createdAt: d(2025,11,15) },
  { id: "act-34", title: "Proposta - Fast Burger", type: "email", status: "completed", dueDate: d(2025,11,20), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w17", completedAt: d(2025,11,20), createdAt: d(2025,11,17) },
  { id: "act-35", title: "Follow-up - Clube Recreativo", type: "follow-up", status: "completed", dueDate: d(2025,11,22), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w18", completedAt: d(2025,11,22), createdAt: d(2025,11,19) },
  { id: "act-36", title: "Ligar - Pizzaria Napoli", type: "call", status: "completed", dueDate: d(2025,11,24), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w19", completedAt: d(2025,11,24), createdAt: d(2025,11,21) },
  { id: "act-37", title: "Fechamento - Steakhouse Premium", type: "meeting", status: "completed", dueDate: d(2025,11,27), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w20", completedAt: d(2025,11,27), createdAt: d(2025,11,24) },
  // Completed activities (October 2025)
  { id: "act-38", title: "Reunião - Churrascaria Fogo Alto", type: "meeting", status: "completed", dueDate: d(2025,10,12), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w07", completedAt: d(2025,10,12), createdAt: d(2025,10,9) },
  { id: "act-39", title: "Visita - Verde Vida", type: "visit", status: "completed", dueDate: d(2025,10,15), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w08", completedAt: d(2025,10,15), createdAt: d(2025,10,12) },
  { id: "act-40", title: "Proposta - Escola Gastronomia", type: "email", status: "completed", dueDate: d(2025,10,17), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w09", completedAt: d(2025,10,17), createdAt: d(2025,10,14) },
  { id: "act-41", title: "Negociação - Pousadas Sul", type: "meeting", status: "completed", dueDate: d(2025,10,20), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w10", completedAt: d(2025,10,20), createdAt: d(2025,10,17) },
  { id: "act-42", title: "Ligar - Food Truck Urbano", type: "call", status: "completed", dueDate: d(2025,10,22), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w11", completedAt: d(2025,10,22), createdAt: d(2025,10,19) },
  { id: "act-43", title: "Reunião - Rooftop Bar", type: "meeting", status: "completed", dueDate: d(2025,10,24), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w12", completedAt: d(2025,10,24), createdAt: d(2025,10,21) },
  { id: "act-44", title: "Follow-up - Doce Mel", type: "follow-up", status: "completed", dueDate: d(2025,10,26), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w13", completedAt: d(2025,10,26), createdAt: d(2025,10,23) },
  // Completed activities (September 2025)
  { id: "act-45", title: "Primeira reunião - Sabor da Terra", type: "meeting", status: "completed", dueDate: d(2025,9,10), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w01", completedAt: d(2025,9,10), createdAt: d(2025,9,7) },
  { id: "act-46", title: "Degustação - Hotel Beira Mar", type: "meeting", status: "completed", dueDate: d(2025,9,12), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w02", completedAt: d(2025,9,12), createdAt: d(2025,9,9) },
  { id: "act-47", title: "Proposta - Delivery Gourmet", type: "email", status: "completed", dueDate: d(2025,9,15), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w03", completedAt: d(2025,9,15), createdAt: d(2025,9,12) },
  { id: "act-48", title: "Ligar - Trigo Dourado", type: "call", status: "completed", dueDate: d(2025,9,18), responsibleId: "user-6", responsibleName: "Marcos Pereira", opportunityId: "opp-w04", completedAt: d(2025,9,18), createdAt: d(2025,9,15) },
  { id: "act-49", title: "Reunião - Bar do Jorge", type: "meeting", status: "completed", dueDate: d(2025,9,20), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-w05", completedAt: d(2025,9,20), createdAt: d(2025,9,17) },
  { id: "act-50", title: "Fechamento - Cantina ABC", type: "meeting", status: "completed", dueDate: d(2025,9,25), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-w06", completedAt: d(2025,9,25), createdAt: d(2025,9,22) },
  // Cancelled activities
  { id: "act-51", title: "Reunião cancelada - Hotel Centro Executivo", type: "meeting", status: "cancelled", description: "Cliente desistiu da negociação", dueDate: d(2025,10,8), responsibleId: "user-4", responsibleName: "Juliana Costa", opportunityId: "opp-l02", createdAt: d(2025,10,5) },
  { id: "act-52", title: "Visita cancelada - Cantina Empresa Tech", type: "visit", status: "cancelled", description: "Projeto cancelado pelo cliente", dueDate: d(2025,12,5), responsibleId: "user-3", responsibleName: "Lucas Oliveira", opportunityId: "opp-l07", createdAt: d(2025,12,1) },
];
