import type { AuditEvent } from "@/types";

// ===== Mock Audit Log =====

export const mockAuditLog: AuditEvent[] = [
  { id: "audit-1", action: "Ganhou oportunidade", entity: "opportunity", entityId: "opp-w40", entityName: "Laticinios - Padaria Artesanal Fermento", userId: "user-6", userName: "Marcos Pereira", details: "Oportunidade marcada como ganha. Valor: R$ 60.000,00", timestamp: "2026-02-08T15:30:00" },
  { id: "audit-2", action: "Adicionou cliente", entity: "client", entityId: "client-new5", entityName: "Padaria Artesanal Fermento EIRELI", userId: "user-7", userName: "Carolina Santos", details: "Novo cliente cadastrado no estágio 'Implantação'.", timestamp: "2026-02-08T15:35:00" },
  { id: "audit-3", action: "Ganhou oportunidade", entity: "opportunity", entityId: "opp-w39", entityName: "Embalagens - Dark Kitchen Central", userId: "user-3", userName: "Lucas Oliveira", details: "Oportunidade marcada como ganha. Valor: R$ 42.000,00", timestamp: "2026-02-08T10:00:00" },
  { id: "audit-4", action: "Ganhou oportunidade", entity: "opportunity", entityId: "opp-w38", entityName: "Bebidas - Pub Irlandês Dublin", userId: "user-4", userName: "Juliana Costa", details: "Oportunidade marcada como ganha. Valor: R$ 120.000,00", timestamp: "2026-02-08T09:00:00" },
  { id: "audit-5", action: "Completou atividade", entity: "activity", entityId: "act-15", entityName: "Ligar - Pub Dublin confirmação", userId: "user-6", userName: "Marcos Pereira", details: "Atividade de ligação marcada como concluída.", timestamp: "2026-02-08T10:30:00" },
  { id: "audit-6", action: "Criou oportunidade", entity: "opportunity", entityId: "opp-o07", entityName: "Insumos gerais - Hospital Regional Norte", userId: "user-3", userName: "Lucas Oliveira", details: "Nova oportunidade criada no estágio 'Lead In' com valor de R$ 480.000,00.", timestamp: "2026-02-06T11:00:00" },
  { id: "audit-7", action: "Avançou estágio", entity: "opportunity", entityId: "opp-o06", entityName: "Embalagens sustentáveis - Green Food Delivery", userId: "user-6", userName: "Marcos Pereira", details: "Oportunidade movida de 'Negociação' para 'Fechamento'.", timestamp: "2026-02-05T14:00:00" },
  { id: "audit-8", action: "Ganhou oportunidade", entity: "opportunity", entityId: "opp-w37", entityName: "Proteinas - Restaurante Nordestino Sertão", userId: "user-6", userName: "Marcos Pereira", details: "Oportunidade marcada como ganha. Valor: R$ 72.000,00", timestamp: "2026-02-08T08:00:00" },
  { id: "audit-9", action: "Alterou saúde do cliente", entity: "client", entityId: "client-8", entityName: "Restaurante Verde Vida ME", userId: "user-5", userName: "Fernanda Lima", details: "Health score alterado de 'warning' para 'critical' devido a falta de interação.", timestamp: "2026-02-07T10:00:00" },
  { id: "audit-10", action: "Ganhou oportunidade", entity: "opportunity", entityId: "opp-w36", entityName: "Hortifruti - Spa Wellness Center", userId: "user-3", userName: "Lucas Oliveira", details: "Oportunidade marcada como ganha. Valor: R$ 108.000,00", timestamp: "2026-02-06T16:00:00" },
  { id: "audit-11", action: "Ganhou oportunidade", entity: "opportunity", entityId: "opp-w35", entityName: "Carnes premium - Restaurante Paris Bistro", userId: "user-4", userName: "Juliana Costa", details: "Oportunidade marcada como ganha. Valor: R$ 228.000,00", timestamp: "2026-02-07T16:45:00" },
  { id: "audit-12", action: "Perdeu oportunidade", entity: "opportunity", entityId: "opp-l15", entityName: "Insumos - Cantina Faculdade ABC", userId: "user-6", userName: "Marcos Pereira", details: "Oportunidade perdida. Motivo: Licitação não ganha", timestamp: "2026-02-06T11:30:00" },
  { id: "audit-13", action: "Atualizou configuração", entity: "settings", entityId: "config-sla", entityName: "SLA do Pipeline", userId: "user-2", userName: "Camila Ferreira", details: "SLA do estágio 'Proposta Enviada' alterado de 72h para 48h.", timestamp: "2026-02-01T09:00:00" },
  { id: "audit-14", action: "Criou atividade", entity: "activity", entityId: "act-1", entityName: "Ligar para Jean Pierre - alinhar onboarding", userId: "user-5", userName: "Fernanda Lima", details: "Ligação agendada para 10/02 às 10:00.", timestamp: "2026-02-08T08:30:00" },
  { id: "audit-15", action: "Avançou estágio", entity: "opportunity", entityId: "opp-o05", entityName: "Laticinios especiais - Rede Padarias Artesanais", userId: "user-4", userName: "Juliana Costa", details: "Oportunidade movida de 'Proposta Enviada' para 'Negociação'.", timestamp: "2026-02-04T15:00:00" },
];
