import type { Opportunity } from "@/types";

// ═══════════════════════════════════════════════════════════════════
// Pipeline Mock Data — SLA dinâmico relativo a now
// ═══════════════════════════════════════════════════════════════════

export function generateDynamicMockData(
  ownerId = "demo-user",
  ownerName = "Usuário Demo",
): Opportunity[] {
  const now = new Date();
  const h = (hours: number) =>
    new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
  const daysAgo = (days: number) =>
    new Date(now.getTime() - days * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0];
  const daysFromNow = (days: number) =>
    new Date(now.getTime() + days * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0];

  return [
    {
      id: "1",
      title: "Restaurante Bela Vista",
      clientName: "Restaurante Bela Vista Ltda",
      neighborhood: "Altiplano",
      value: 12000,
      monthlyValue: 1000,
      stage: "lead-in",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["food-service", "premium"],
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
      status: "open",
      slaDeadline: h(-6),
    },
    {
      id: "2",
      title: "Padaria Pao Quente",
      clientName: "Padaria Pao Quente ME",
      neighborhood: "Manaíra",
      value: 4800,
      monthlyValue: 400,
      stage: "lead-in",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["panificacao"],
      createdAt: daysAgo(8),
      updatedAt: daysAgo(2),
      status: "open",
      slaDeadline: h(30),
    },
    {
      id: "3",
      title: "Lanchonete do Carlos",
      clientName: "Carlos Almeida ME",
      neighborhood: "Bancários",
      value: 3600,
      monthlyValue: 300,
      stage: "lead-in",
      temperature: "cold",
      responsibleId: "3",
      responsibleName: "Ana Oliveira",
      tags: ["fast-food"],
      createdAt: daysAgo(6),
      updatedAt: daysAgo(5),
      status: "open",
      slaDeadline: h(8),
    },
    {
      id: "4",
      title: "Bar do Ze",
      clientName: "Bar do Ze Ltda",
      neighborhood: "Tambaú",
      value: 8400,
      monthlyValue: 700,
      stage: "contato-feito",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["bar", "noturno"],
      createdAt: daysAgo(8),
      updatedAt: daysAgo(1),
      status: "open",
      slaDeadline: h(52),
    },
    {
      id: "5",
      title: "Pizzaria Napoli",
      clientName: "Napoli Alimentos Ltda",
      neighborhood: "Bessa",
      value: 15000,
      monthlyValue: 1250,
      stage: "contato-feito",
      temperature: "hot",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["pizzaria", "delivery"],
      createdAt: daysAgo(12),
      updatedAt: daysAgo(3),
      status: "open",
      slaDeadline: h(-24),
    },
    {
      id: "6",
      title: "Hotel Sunset",
      clientName: "Hotel Sunset S.A.",
      neighborhood: "Cabo Branco",
      value: 36000,
      monthlyValue: 3000,
      stage: "reuniao-agendada",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["hotelaria"],
      createdAt: daysAgo(20),
      updatedAt: daysAgo(2),
      status: "open",
      expectedCloseDate: daysFromNow(35),
      slaDeadline: h(96),
    },
    {
      id: "7",
      title: "Sorveteria Gelato",
      clientName: "Gelato Artesanal ME",
      neighborhood: "Jardim Oceania",
      value: 7200,
      monthlyValue: 600,
      stage: "reuniao-agendada",
      temperature: "cold",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["sorvetes"],
      createdAt: daysAgo(18),
      updatedAt: daysAgo(10),
      status: "open",
      expectedCloseDate: daysFromNow(20),
      slaDeadline: h(4),
    },
    {
      id: "8",
      title: "Cafe Central",
      clientName: "Cafe Central ME",
      neighborhood: "Centro",
      value: 6000,
      monthlyValue: 500,
      stage: "proposta-enviada",
      temperature: "cold",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["cafeteria"],
      createdAt: daysAgo(30),
      updatedAt: daysAgo(7),
      status: "open",
      expectedCloseDate: daysFromNow(19),
      slaDeadline: h(18),
    },
    {
      id: "9",
      title: "Hamburgueria Smash",
      clientName: "Smash Burger Ltda",
      neighborhood: "Brisamar",
      value: 9600,
      monthlyValue: 800,
      stage: "proposta-enviada",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["hamburgueria", "premium"],
      createdAt: daysAgo(22),
      updatedAt: daysAgo(1),
      status: "open",
      expectedCloseDate: daysFromNow(11),
      slaDeadline: h(72),
    },
    {
      id: "10",
      title: "Pousada Mar Azul",
      clientName: "Pousada Mar Azul ME",
      neighborhood: "Tambaú",
      value: 24000,
      monthlyValue: 2000,
      stage: "negociacao",
      temperature: "hot",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["hotelaria"],
      createdAt: daysAgo(35),
      updatedAt: daysAgo(1),
      status: "open",
      expectedCloseDate: daysFromNow(6),
      slaDeadline: h(120),
    },
    {
      id: "11",
      title: "Doceria Sabor & Arte",
      clientName: "Sabor e Arte Doces Ltda",
      neighborhood: "Torre",
      value: 10800,
      monthlyValue: 900,
      stage: "negociacao",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["confeitaria"],
      createdAt: daysAgo(28),
      updatedAt: daysAgo(4),
      status: "open",
      expectedCloseDate: daysFromNow(16),
      slaDeadline: h(-48),
    },
    {
      id: "12",
      title: "Churrascaria Fogo Bravo",
      clientName: "Fogo Bravo Ltda",
      neighborhood: "Mangabeira",
      value: 18000,
      monthlyValue: 1500,
      stage: "fechamento",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["food-service", "churrascaria"],
      createdAt: daysAgo(50),
      updatedAt: daysAgo(1),
      status: "open",
      expectedCloseDate: daysFromNow(2),
      slaDeadline: h(36),
    },
    {
      id: "13",
      title: "Acai da Praia",
      clientName: "Acai da Praia Franquias S.A.",
      neighborhood: "Intermares",
      value: 42000,
      monthlyValue: 3500,
      stage: "fechamento",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["acai", "franquia"],
      createdAt: daysAgo(60),
      updatedAt: daysAgo(1),
      status: "open",
      expectedCloseDate: daysFromNow(1),
      slaDeadline: h(10),
    },
    {
      id: "14",
      title: "Cantina Bella Nonna",
      clientName: "Bella Nonna Restaurante Ltda",
      neighborhood: "Expedicionários",
      value: 14400,
      monthlyValue: 1200,
      stage: "lead-in",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["italiano", "restaurante"],
      createdAt: daysAgo(5),
      updatedAt: daysAgo(1),
      status: "open",
      slaDeadline: h(40),
    },
    {
      id: "15",
      title: "Distribuidora Nordeste Bebidas",
      clientName: "Nordeste Bebidas Ltda",
      neighborhood: "Cristo Redentor",
      value: 28000,
      monthlyValue: 2333,
      stage: "lead-in",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["distribuicao", "bebidas"],
      createdAt: daysAgo(3),
      updatedAt: daysAgo(0),
      status: "open",
      slaDeadline: h(42),
    },
    {
      id: "16",
      title: "Farmacia Vida & Saude",
      clientName: "Vida e Saude Farmacias ME",
      neighborhood: "Agua Fria",
      value: 5400,
      monthlyValue: 450,
      stage: "lead-in",
      temperature: "cold",
      responsibleId: "3",
      responsibleName: "Ana Oliveira",
      tags: ["farmacia", "saude"],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      status: "open",
      slaDeadline: h(20),
    },
    {
      id: "17",
      title: "Auto Pecas Joao Paulo",
      clientName: "JP Auto Pecas Ltda",
      neighborhood: "Jose Americo",
      value: 9000,
      monthlyValue: 750,
      stage: "lead-in",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["automotivo"],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(0),
      status: "open",
      slaDeadline: h(46),
    },
    {
      id: "18",
      title: "Clinica Odonto Plus",
      clientName: "Odonto Plus Servicos Medicos SS",
      neighborhood: "Manaíra",
      value: 21600,
      monthlyValue: 1800,
      stage: "contato-feito",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["saude", "odontologia"],
      createdAt: daysAgo(10),
      updatedAt: daysAgo(1),
      status: "open",
      slaDeadline: h(60),
    },
    {
      id: "19",
      title: "Escola Infantil Pequenos Genios",
      clientName: "Pequenos Genios Educacao Ltda",
      neighborhood: "Bancários",
      value: 16800,
      monthlyValue: 1400,
      stage: "contato-feito",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["educacao", "infantil"],
      createdAt: daysAgo(7),
      updatedAt: daysAgo(2),
      status: "open",
      slaDeadline: h(48),
    },
    {
      id: "20",
      title: "Petshop Amigo Fiel",
      clientName: "Amigo Fiel Petshop ME",
      neighborhood: "Tambaú",
      value: 3600,
      monthlyValue: 300,
      stage: "contato-feito",
      temperature: "cold",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["pet", "varejo"],
      createdAt: daysAgo(14),
      updatedAt: daysAgo(8),
      status: "open",
      slaDeadline: h(-12),
    },
    {
      id: "21",
      title: "Construtora Horizonte",
      clientName: "Horizonte Engenharia S.A.",
      neighborhood: "Altiplano",
      value: 60000,
      monthlyValue: 5000,
      stage: "contato-feito",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["construcao", "premium"],
      createdAt: daysAgo(9),
      updatedAt: daysAgo(0),
      status: "open",
      slaDeadline: h(36),
    },
    {
      id: "22",
      title: "Loja de Roupas Estilo",
      clientName: "Estilo Moda Ltda",
      neighborhood: "Bessa",
      value: 7200,
      monthlyValue: 600,
      stage: "reuniao-agendada",
      temperature: "warm",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["moda", "varejo"],
      createdAt: daysAgo(15),
      updatedAt: daysAgo(3),
      status: "open",
      expectedCloseDate: daysFromNow(25),
      slaDeadline: h(80),
    },
    {
      id: "23",
      title: "Grafica Express Print",
      clientName: "Express Print Grafica ME",
      neighborhood: "Centro",
      value: 4800,
      monthlyValue: 400,
      stage: "reuniao-agendada",
      temperature: "cold",
      responsibleId: "3",
      responsibleName: "Ana Oliveira",
      tags: ["grafica", "servicos"],
      createdAt: daysAgo(21),
      updatedAt: daysAgo(12),
      status: "open",
      expectedCloseDate: daysFromNow(18),
      slaDeadline: h(-8),
    },
    {
      id: "24",
      title: "Academia Corpo em Forma",
      clientName: "Corpo em Forma Fitness Ltda",
      neighborhood: "Jardim Oceania",
      value: 19200,
      monthlyValue: 1600,
      stage: "reuniao-agendada",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["fitness", "saude"],
      createdAt: daysAgo(16),
      updatedAt: daysAgo(1),
      status: "open",
      expectedCloseDate: daysFromNow(14),
      slaDeadline: h(70),
    },
    {
      id: "25",
      title: "Supermercado Bom Preco",
      clientName: "Bom Preco Supermercados Ltda",
      neighborhood: "Mangabeira",
      value: 48000,
      monthlyValue: 4000,
      stage: "proposta-enviada",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["supermercado", "premium"],
      createdAt: daysAgo(25),
      updatedAt: daysAgo(2),
      status: "open",
      expectedCloseDate: daysFromNow(10),
      slaDeadline: h(48),
    },
    {
      id: "26",
      title: "Escritorio Contabil Fiscal",
      clientName: "Fiscal Contabilidade SS",
      neighborhood: "Torre",
      value: 10800,
      monthlyValue: 900,
      stage: "proposta-enviada",
      temperature: "warm",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["contabilidade", "servicos"],
      createdAt: daysAgo(19),
      updatedAt: daysAgo(5),
      status: "open",
      expectedCloseDate: daysFromNow(15),
      slaDeadline: h(24),
    },
    {
      id: "27",
      title: "Imobiliaria Casa Nova",
      clientName: "Casa Nova Imoveis Ltda",
      neighborhood: "Cabo Branco",
      value: 30000,
      monthlyValue: 2500,
      stage: "proposta-enviada",
      temperature: "cold",
      responsibleId: "3",
      responsibleName: "Ana Oliveira",
      tags: ["imobiliaria"],
      createdAt: daysAgo(32),
      updatedAt: daysAgo(15),
      status: "open",
      expectedCloseDate: daysFromNow(22),
      slaDeadline: h(-36),
    },
    {
      id: "28",
      title: "Clinica Veterinaria PetCare",
      clientName: "PetCare Vet Ltda",
      neighborhood: "Brisamar",
      value: 8400,
      monthlyValue: 700,
      stage: "negociacao",
      temperature: "warm",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["veterinaria", "pet"],
      createdAt: daysAgo(26),
      updatedAt: daysAgo(3),
      status: "open",
      expectedCloseDate: daysFromNow(8),
      slaDeadline: h(96),
    },
    {
      id: "29",
      title: "Posto de Gasolina Estrela",
      clientName: "Estrela Combustiveis Ltda",
      neighborhood: "Valentina",
      value: 36000,
      monthlyValue: 3000,
      stage: "negociacao",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["combustiveis", "premium"],
      createdAt: daysAgo(40),
      updatedAt: daysAgo(1),
      status: "open",
      expectedCloseDate: daysFromNow(4),
      slaDeadline: h(60),
    },
    {
      id: "30",
      title: "Salao de Beleza Glamour",
      clientName: "Glamour Beauty Ltda",
      neighborhood: "Manaíra",
      value: 6000,
      monthlyValue: 500,
      stage: "negociacao",
      temperature: "cold",
      responsibleId: "3",
      responsibleName: "Ana Oliveira",
      tags: ["beleza", "estetica"],
      createdAt: daysAgo(33),
      updatedAt: daysAgo(14),
      status: "open",
      expectedCloseDate: daysFromNow(12),
      slaDeadline: h(-72),
    },
    {
      id: "31",
      title: "Laboratorio de Analises BioLab",
      clientName: "BioLab Analises Clinicas Ltda",
      neighborhood: "Centro",
      value: 25200,
      monthlyValue: 2100,
      stage: "fechamento",
      temperature: "hot",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["saude", "laboratorio"],
      createdAt: daysAgo(55),
      updatedAt: daysAgo(0),
      status: "open",
      expectedCloseDate: daysFromNow(3),
      slaDeadline: h(24),
    },
    {
      id: "32",
      title: "Coworking Space Hub",
      clientName: "Hub Coworking Ltda",
      neighborhood: "Altiplano",
      value: 14400,
      monthlyValue: 1200,
      stage: "fechamento",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["coworking", "tecnologia"],
      createdAt: daysAgo(45),
      updatedAt: daysAgo(2),
      status: "open",
      expectedCloseDate: daysFromNow(5),
      slaDeadline: h(40),
    },
    {
      id: "33",
      title: "Agencia de Viagens TurBrasil",
      clientName: "TurBrasil Viagens e Turismo Ltda",
      neighborhood: "Tambaú",
      value: 20400,
      monthlyValue: 1700,
      stage: "lead-in",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["turismo", "viagens"],
      createdAt: daysAgo(4),
      updatedAt: daysAgo(0),
      status: "open",
      slaDeadline: h(38),
    },
    {
      id: "34",
      title: "Oficina Mecanica TurboForce",
      clientName: "TurboForce Auto Service ME",
      neighborhood: "Jose Americo",
      value: 7800,
      monthlyValue: 650,
      stage: "contato-feito",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["automotivo", "servicos"],
      createdAt: daysAgo(11),
      updatedAt: daysAgo(4),
      status: "open",
      slaDeadline: h(28),
    },
    {
      id: "35",
      title: "Restaurante Sabor do Sertao",
      clientName: "Sabor do Sertao Gastronomia Ltda",
      neighborhood: "Brisamar",
      value: 16200,
      monthlyValue: 1350,
      stage: "reuniao-agendada",
      temperature: "hot",
      responsibleId: "2",
      responsibleName: "Joao Santos",
      tags: ["food-service", "regional"],
      createdAt: daysAgo(13),
      updatedAt: daysAgo(1),
      status: "open",
      expectedCloseDate: daysFromNow(22),
      slaDeadline: h(88),
    },
    {
      id: "36",
      title: "Papelaria e Presentes Art Paper",
      clientName: "Art Paper Papelaria ME",
      neighborhood: "Torre",
      value: 3000,
      monthlyValue: 250,
      stage: "proposta-enviada",
      temperature: "cold",
      responsibleId: "3",
      responsibleName: "Ana Oliveira",
      tags: ["papelaria", "varejo"],
      createdAt: daysAgo(27),
      updatedAt: daysAgo(10),
      status: "open",
      expectedCloseDate: daysFromNow(20),
      slaDeadline: h(-18),
    },
    {
      id: "37",
      title: "Startup Tech Innova",
      clientName: "Innova Tecnologia S.A.",
      neighborhood: "Altiplano",
      value: 72000,
      monthlyValue: 6000,
      stage: "negociacao",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["tecnologia", "premium", "startup"],
      createdAt: daysAgo(38),
      updatedAt: daysAgo(0),
      status: "open",
      expectedCloseDate: daysFromNow(7),
      slaDeadline: h(100),
    },
    {
      id: "38",
      title: "Padaria Artesanal Trigo & Mel",
      clientName: "Trigo e Mel Panificacao ME",
      neighborhood: "Agua Fria",
      value: 5400,
      monthlyValue: 450,
      stage: "fechamento",
      temperature: "warm",
      responsibleId: "3",
      responsibleName: "Ana Oliveira",
      tags: ["panificacao", "artesanal"],
      createdAt: daysAgo(48),
      updatedAt: daysAgo(1),
      status: "open",
      expectedCloseDate: daysFromNow(2),
      slaDeadline: h(18),
    },
    {
      id: "39",
      title: "Centro Automotivo Premium",
      clientName: "Premium Auto Center Ltda",
      neighborhood: "Cabo Branco",
      value: 33600,
      monthlyValue: 2800,
      stage: "proposta-enviada",
      temperature: "warm",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["automotivo", "premium"],
      createdAt: daysAgo(17),
      updatedAt: daysAgo(3),
      status: "open",
      expectedCloseDate: daysFromNow(13),
      slaDeadline: h(56),
    },
    {
      id: "40",
      title: "Consultoria RH Talentos",
      clientName: "Talentos RH Consultoria SS",
      neighborhood: "Expedicionários",
      value: 12600,
      monthlyValue: 1050,
      stage: "contato-feito",
      temperature: "hot",
      responsibleId: ownerId,
      responsibleName: ownerName,
      tags: ["consultoria", "rh"],
      createdAt: daysAgo(6),
      updatedAt: daysAgo(0),
      status: "open",
      slaDeadline: h(55),
    },
  ];
}
