import type { NegotiationRound } from "@/types";
import { daysAgo } from "./helpers";

// ===== Negotiation Mock Data (20 rounds across open opportunities) =====

export const mockNegotiationRounds: NegotiationRound[] = [
  // opp-o01 — Carnes nobres - Restaurante Fazenda Velha (negociacao)
  {
    id: "round-1",
    opportunityId: "opp-o01",
    type: "proposal",
    authorId: "user-3",
    authorName: "Lucas Oliveira",
    createdAt: daysAgo(15),
    monthlyValue: 8000,
    totalValue: 96000,
    setupValue: 3000,
    termMonths: 12,
    conditions: ["Contrato anual", "Pagamento mensal"],
    status: "active",
  },
  {
    id: "round-2",
    opportunityId: "opp-o01",
    type: "counter",
    authorId: "client-28",
    authorName: "Joaquim Fazenda",
    createdAt: daysAgo(13),
    monthlyValue: 7000,
    totalValue: 84000,
    setupValue: 0,
    termMonths: 12,
    conditions: ["Isenção de setup", "Desconto de 12%"],
    details: "Cliente pede remoção da taxa de implantação.",
    status: "active",
  },
  {
    id: "round-3",
    opportunityId: "opp-o01",
    type: "internal",
    authorId: "user-4",
    authorName: "Juliana Costa",
    createdAt: daysAgo(12),
    monthlyValue: 7500,
    totalValue: 90000,
    setupValue: 1500,
    termMonths: 12,
    conditions: ["Setup com 50% desconto", "Mensalidade R$ 7.500"],
    details: "Proposta de meio termo para fechar rápido.",
    status: "active",
  },

  // opp-o02 — Hortifruti completo - Hotel Montanha Resort (proposta-enviada)
  {
    id: "round-4",
    opportunityId: "opp-o02",
    type: "proposal",
    authorId: "user-4",
    authorName: "Juliana Costa",
    createdAt: daysAgo(20),
    monthlyValue: 12000,
    totalValue: 144000,
    setupValue: 5000,
    termMonths: 12,
    conditions: ["Entrega diária", "Mínimo mensal R$ 10.000"],
    status: "active",
  },
  {
    id: "round-5",
    opportunityId: "opp-o02",
    type: "counter",
    authorId: "client-29",
    authorName: "Carlos Montanha",
    createdAt: daysAgo(18),
    monthlyValue: 10000,
    totalValue: 120000,
    setupValue: 0,
    termMonths: 12,
    conditions: ["Sem mínimo mensal", "Setup gratuito"],
    details: "Hotel prefere flexibilidade nos volumes mensais.",
    status: "active",
  },

  // opp-o03 — Açaí e polpas - Rede Açaí Beach (reuniao-agendada)
  {
    id: "round-6",
    opportunityId: "opp-o03",
    type: "proposal",
    authorId: "user-6",
    authorName: "Marcos Pereira",
    createdAt: daysAgo(10),
    monthlyValue: 5500,
    totalValue: 66000,
    setupValue: 2000,
    termMonths: 12,
    conditions: ["Entrega semanal", "Padrão premium"],
    status: "active",
  },

  // opp-o04 — Insumos cervejeiros - Cervejaria Artesanal Hop (contato-feito)
  {
    id: "round-7",
    opportunityId: "opp-o04",
    type: "proposal",
    authorId: "user-3",
    authorName: "Lucas Oliveira",
    createdAt: daysAgo(8),
    monthlyValue: 4000,
    totalValue: 48000,
    setupValue: 1000,
    termMonths: 12,
    conditions: ["Insumos importados", "Entrega quinzenal"],
    status: "active",
  },

  // opp-o05 — Laticínios especiais - Rede Padarias Artesanais (negociacao)
  {
    id: "round-8",
    opportunityId: "opp-o05",
    type: "proposal",
    authorId: "user-4",
    authorName: "Juliana Costa",
    createdAt: daysAgo(25),
    monthlyValue: 6000,
    totalValue: 72000,
    setupValue: 2500,
    termMonths: 12,
    conditions: ["Contrato anual", "Frete incluso"],
    status: "superseded",
  },
  {
    id: "round-9",
    opportunityId: "opp-o05",
    type: "counter",
    authorId: "client-32",
    authorName: "Ana Grão",
    createdAt: daysAgo(22),
    monthlyValue: 5000,
    totalValue: 60000,
    setupValue: 0,
    termMonths: 6,
    conditions: ["Contrato semestral", "Sem fidelidade"],
    details: "Prefere período menor para testar a parceria.",
    status: "active",
  },
  {
    id: "round-10",
    opportunityId: "opp-o05",
    type: "internal",
    authorId: "user-3",
    authorName: "Lucas Oliveira",
    createdAt: daysAgo(20),
    monthlyValue: 5500,
    totalValue: 66000,
    setupValue: 1000,
    termMonths: 6,
    conditions: ["Semestral com renovação auto", "Setup reduzido"],
    details: "Aceitar semestral com setup simbólico.",
    status: "active",
  },

  // opp-o06 — Embalagens sustentáveis - Green Food Delivery (fechamento)
  {
    id: "round-11",
    opportunityId: "opp-o06",
    type: "proposal",
    authorId: "user-6",
    authorName: "Marcos Pereira",
    createdAt: daysAgo(30),
    monthlyValue: 3500,
    totalValue: 42000,
    setupValue: 1500,
    termMonths: 12,
    conditions: ["Embalagens biodegradáveis", "Estoque mínimo"],
    status: "superseded",
  },
  {
    id: "round-12",
    opportunityId: "opp-o06",
    type: "counter",
    authorId: "client-33",
    authorName: "Ahmed Habibi",
    createdAt: daysAgo(27),
    monthlyValue: 3000,
    totalValue: 36000,
    setupValue: 0,
    termMonths: 12,
    conditions: ["Sem estoque mínimo", "Desconto volume"],
    status: "active",
  },
  {
    id: "round-13",
    opportunityId: "opp-o06",
    type: "agreement",
    authorId: "user-6",
    authorName: "Marcos Pereira",
    createdAt: daysAgo(5),
    monthlyValue: 3200,
    totalValue: 38400,
    setupValue: 500,
    termMonths: 12,
    conditions: ["Estoque flexível", "Setup simbólico"],
    isFinal: true,
    status: "active",
  },

  // opp-o07 — Insumos gerais - Hospital Regional Norte (lead-in)
  {
    id: "round-14",
    opportunityId: "opp-o07",
    type: "proposal",
    authorId: "user-3",
    authorName: "Lucas Oliveira",
    createdAt: daysAgo(5),
    monthlyValue: 40000,
    totalValue: 480000,
    setupValue: 10000,
    termMonths: 12,
    conditions: ["Licitação", "Entrega diária", "Certificações sanitárias"],
    status: "active",
  },

  // opp-o08 — Proteínas - Steakhouse Premium (proposta-enviada)
  {
    id: "round-15",
    opportunityId: "opp-o08",
    type: "proposal",
    authorId: "user-4",
    authorName: "Juliana Costa",
    createdAt: daysAgo(12),
    monthlyValue: 9000,
    totalValue: 108000,
    setupValue: 3000,
    termMonths: 12,
    conditions: ["Cortes premium importados", "Entrega 3x/semana"],
    status: "active",
  },
  {
    id: "round-16",
    opportunityId: "opp-o08",
    type: "counter",
    authorId: "client-20",
    authorName: "Victor Premium",
    createdAt: daysAgo(10),
    monthlyValue: 8000,
    totalValue: 96000,
    setupValue: 0,
    termMonths: 12,
    conditions: ["Sem setup", "Volume mínimo menor"],
    details: "Quer testar mix de produtos antes de comprometer volume.",
    status: "active",
  },

  // opp-o09 — Resort all-inclusive - Resort Praia Azul (reuniao-agendada)
  {
    id: "round-17",
    opportunityId: "opp-o09",
    type: "proposal",
    authorId: "user-3",
    authorName: "Lucas Oliveira",
    createdAt: daysAgo(7),
    monthlyValue: 15000,
    totalValue: 180000,
    setupValue: 8000,
    termMonths: 12,
    conditions: ["Fornecimento completo all-inclusive", "Logística dedicada"],
    status: "active",
  },

  // opp-o10 — Eventos - Casa de Shows Arena (negociacao)
  {
    id: "round-18",
    opportunityId: "opp-o10",
    type: "proposal",
    authorId: "user-6",
    authorName: "Marcos Pereira",
    createdAt: daysAgo(18),
    monthlyValue: 7000,
    totalValue: 84000,
    setupValue: 4000,
    termMonths: 12,
    conditions: ["Fornecimento por evento", "Cardápio variável"],
    status: "active",
  },
  {
    id: "round-19",
    opportunityId: "opp-o10",
    type: "counter",
    authorId: "client-24",
    authorName: "Rogério Arena",
    createdAt: daysAgo(15),
    monthlyValue: 6000,
    totalValue: 72000,
    setupValue: 2000,
    termMonths: 12,
    conditions: ["Setup menor", "Pagamento pós-evento"],
    details: "Prefere pagar após cada evento realizado.",
    status: "active",
  },
  {
    id: "round-20",
    opportunityId: "opp-o10",
    type: "internal",
    authorId: "user-4",
    authorName: "Juliana Costa",
    createdAt: daysAgo(14),
    monthlyValue: 6500,
    totalValue: 78000,
    setupValue: 2500,
    termMonths: 12,
    conditions: ["Setup reduzido", "Pagamento 50% antecipado"],
    details: "Encontro intermediário para viabilizar o modelo.",
    status: "active",
  },
];
