import type { Opportunity } from "@/types";
import { d } from "./helpers";

// ===== Mock Opportunities (65 total: 40 won, 15 lost, 10 open) =====

export const mockOpportunities: Opportunity[] = [
  // === WON OPPORTUNITIES (40) - September 2025 to February 2026 ===
  // September 2025 (6 won)
  {
    id: "opp-w01",
    title: "Hortifruti premium - Restaurante Sabor da Terra",
    clientName: "Restaurante Sabor da Terra Ltda",
    clientId: "client-1",
    value: 84000,
    monthlyValue: 7000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["hortifruti", "restaurante"],
    createdAt: d(2025, 9, 2),
    updatedAt: d(2025, 9, 18),
    expectedCloseDate: d(2025, 9, 20),
    status: "won",
    source: "Indicacao",
    notes: "Contrato anual fechado",
  },
  {
    id: "opp-w02",
    title: "Proteinas congeladas - Hotel Beira Mar",
    clientName: "Hotel Beira Mar SA",
    clientId: "client-2",
    value: 180000,
    monthlyValue: 15000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["proteinas", "hotel"],
    createdAt: d(2025, 9, 5),
    updatedAt: d(2025, 9, 22),
    expectedCloseDate: d(2025, 9, 25),
    status: "won",
    source: "Feira Alimenta",
    notes: "Cliente premium",
  },
  {
    id: "opp-w03",
    title: "Embalagens eco - Delivery Gourmet",
    clientName: "Delivery Gourmet ME",
    clientId: "client-3",
    value: 36000,
    monthlyValue: 3000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["embalagens", "delivery"],
    createdAt: d(2025, 9, 8),
    updatedAt: d(2025, 9, 25),
    expectedCloseDate: d(2025, 9, 28),
    status: "won",
    source: "Site",
  },
  {
    id: "opp-w04",
    title: "Laticinios - Padaria Trigo Dourado",
    clientName: "Padaria Trigo Dourado EIRELI",
    clientId: "client-4",
    value: 48000,
    monthlyValue: 4000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["laticinios", "padaria"],
    createdAt: d(2025, 9, 10),
    updatedAt: d(2025, 9, 26),
    expectedCloseDate: d(2025, 9, 28),
    status: "won",
    source: "Google Ads",
  },
  {
    id: "opp-w05",
    title: "Bebidas - Bar do Jorge",
    clientName: "Bar do Jorge Ltda",
    clientId: "client-5",
    value: 60000,
    monthlyValue: 5000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["bebidas", "bar"],
    createdAt: d(2025, 9, 12),
    updatedAt: d(2025, 9, 28),
    expectedCloseDate: d(2025, 9, 30),
    status: "won",
    source: "Indicacao",
  },
  {
    id: "opp-w06",
    title: "Insumos gerais - Cantina Escolar ABC",
    clientName: "Cantina Escolar ABC",
    clientId: "client-6",
    value: 72000,
    monthlyValue: 6000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["insumos", "escola"],
    createdAt: d(2025, 9, 15),
    updatedAt: d(2025, 9, 29),
    expectedCloseDate: d(2025, 9, 30),
    status: "won",
    source: "Licitacao",
  },
  // October 2025 (7 won)
  {
    id: "opp-w07",
    title: "Carnes nobres - Churrascaria Fogo Alto",
    clientName: "Churrascaria Fogo Alto SA",
    clientId: "client-7",
    value: 240000,
    monthlyValue: 20000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["carnes", "churrascaria"],
    createdAt: d(2025, 10, 1),
    updatedAt: d(2025, 10, 18),
    expectedCloseDate: d(2025, 10, 20),
    status: "won",
    source: "Feira Alimenta",
  },
  {
    id: "opp-w08",
    title: "Hortifruti organico - Restaurante Verde Vida",
    clientName: "Restaurante Verde Vida ME",
    clientId: "client-8",
    value: 96000,
    monthlyValue: 8000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["hortifruti", "organico"],
    createdAt: d(2025, 10, 3),
    updatedAt: d(2025, 10, 20),
    expectedCloseDate: d(2025, 10, 22),
    status: "won",
    source: "LinkedIn",
  },
  {
    id: "opp-w09",
    title: "Utensilios - Escola Gastronomia SP",
    clientName: "Escola Gastronomia SP",
    clientId: "client-9",
    value: 85000,
    monthlyValue: 7083,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["utensilios", "escola"],
    createdAt: d(2025, 10, 5),
    updatedAt: d(2025, 10, 22),
    expectedCloseDate: d(2025, 10, 25),
    status: "won",
    source: "Site",
  },
  {
    id: "opp-w10",
    title: "Congelados - Rede Pousadas Sul",
    clientName: "Rede Pousadas Sul Ltda",
    clientId: "client-10",
    value: 144000,
    monthlyValue: 12000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["congelados", "pousada"],
    createdAt: d(2025, 10, 8),
    updatedAt: d(2025, 10, 25),
    expectedCloseDate: d(2025, 10, 28),
    status: "won",
    source: "Google Ads",
  },
  {
    id: "opp-w11",
    title: "Embalagens - Food Truck Urbano",
    clientName: "Food Truck Urbano ME",
    clientId: "client-11",
    value: 24000,
    monthlyValue: 2000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["embalagens", "foodtruck"],
    createdAt: d(2025, 10, 10),
    updatedAt: d(2025, 10, 26),
    expectedCloseDate: d(2025, 10, 28),
    status: "won",
    source: "Indicacao",
  },
  {
    id: "opp-w12",
    title: "Bebidas premium - Rooftop Bar",
    clientName: "Rooftop Bar SA",
    clientId: "client-12",
    value: 120000,
    monthlyValue: 10000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["bebidas", "bar", "premium"],
    createdAt: d(2025, 10, 12),
    updatedAt: d(2025, 10, 28),
    expectedCloseDate: d(2025, 10, 30),
    status: "won",
    source: "Indicacao",
  },
  {
    id: "opp-w13",
    title: "Laticinios especiais - Confeitaria Doce Mel",
    clientName: "Confeitaria Doce Mel EIRELI",
    clientId: "client-13",
    value: 42000,
    monthlyValue: 3500,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["laticinios", "confeitaria"],
    createdAt: d(2025, 10, 15),
    updatedAt: d(2025, 10, 30),
    expectedCloseDate: d(2025, 10, 31),
    status: "won",
    source: "Site",
  },
  // November 2025 (7 won)
  {
    id: "opp-w14",
    title: "Proteinas - Restaurante Executivo Prime",
    clientName: "Restaurante Executivo Prime Ltda",
    clientId: "client-14",
    value: 156000,
    monthlyValue: 13000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["proteinas", "executivo"],
    createdAt: d(2025, 11, 1),
    updatedAt: d(2025, 11, 18),
    expectedCloseDate: d(2025, 11, 20),
    status: "won",
    source: "LinkedIn",
  },
  {
    id: "opp-w15",
    title: "Hortifruti - Buffet Casamento Real",
    clientName: "Buffet Casamento Real SA",
    clientId: "client-15",
    value: 180000,
    monthlyValue: 15000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["hortifruti", "buffet", "eventos"],
    createdAt: d(2025, 11, 3),
    updatedAt: d(2025, 11, 20),
    expectedCloseDate: d(2025, 11, 22),
    status: "won",
    source: "Feira Alimenta",
  },
  {
    id: "opp-w16",
    title: "Insumos - Hospital Santa Cruz",
    clientName: "Hospital Santa Cruz",
    clientId: "client-16",
    value: 288000,
    monthlyValue: 24000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["insumos", "hospital", "institucional"],
    createdAt: d(2025, 11, 5),
    updatedAt: d(2025, 11, 22),
    expectedCloseDate: d(2025, 11, 25),
    status: "won",
    source: "Licitacao",
  },
  {
    id: "opp-w17",
    title: "Congelados - Rede Fast Burger",
    clientName: "Rede Fast Burger Ltda",
    clientId: "client-17",
    value: 108000,
    monthlyValue: 9000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["congelados", "fastfood"],
    createdAt: d(2025, 11, 8),
    updatedAt: d(2025, 11, 25),
    expectedCloseDate: d(2025, 11, 28),
    status: "won",
    source: "Google Ads",
  },
  {
    id: "opp-w18",
    title: "Bebidas - Clube Recreativo Central",
    clientName: "Clube Recreativo Central",
    clientId: "client-18",
    value: 96000,
    monthlyValue: 8000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["bebidas", "clube"],
    createdAt: d(2025, 11, 10),
    updatedAt: d(2025, 11, 26),
    expectedCloseDate: d(2025, 11, 28),
    status: "won",
    source: "Indicacao",
  },
  {
    id: "opp-w19",
    title: "Embalagens - Pizzaria Napoli",
    clientName: "Pizzaria Napoli ME",
    clientId: "client-19",
    value: 30000,
    monthlyValue: 2500,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["embalagens", "pizzaria"],
    createdAt: d(2025, 11, 12),
    updatedAt: d(2025, 11, 28),
    expectedCloseDate: d(2025, 11, 30),
    status: "won",
    source: "Site",
  },
  {
    id: "opp-w20",
    title: "Carnes - Steakhouse Premium",
    clientName: "Steakhouse Premium SA",
    clientId: "client-20",
    value: 300000,
    monthlyValue: 25000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["carnes", "premium"],
    createdAt: d(2025, 11, 15),
    updatedAt: d(2025, 11, 29),
    expectedCloseDate: d(2025, 11, 30),
    status: "won",
    source: "Indicacao",
  },
  // December 2025 (7 won)
  {
    id: "opp-w21",
    title: "Hortifruti - Resort Praia Azul",
    clientName: "Resort Praia Azul SA",
    clientId: "client-21",
    value: 216000,
    monthlyValue: 18000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["hortifruti", "resort"],
    createdAt: d(2025, 12, 1),
    updatedAt: d(2025, 12, 18),
    expectedCloseDate: d(2025, 12, 20),
    status: "won",
    source: "Feira Alimenta",
  },
  {
    id: "opp-w22",
    title: "Proteinas - Restaurante Japonês Sushi Ya",
    clientName: "Sushi Ya Ltda",
    clientId: "client-22",
    value: 132000,
    monthlyValue: 11000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["proteinas", "japones"],
    createdAt: d(2025, 12, 3),
    updatedAt: d(2025, 12, 19),
    expectedCloseDate: d(2025, 12, 22),
    status: "won",
    source: "LinkedIn",
  },
  {
    id: "opp-w23",
    title: "Laticinios - Rede Gelaterias Itália",
    clientName: "Rede Gelaterias Itália Ltda",
    clientId: "client-23",
    value: 72000,
    monthlyValue: 6000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["laticinios", "gelateria"],
    createdAt: d(2025, 12, 5),
    updatedAt: d(2025, 12, 20),
    expectedCloseDate: d(2025, 12, 23),
    status: "won",
    source: "Site",
  },
  {
    id: "opp-w24",
    title: "Bebidas - Casa de Shows Arena",
    clientName: "Casa de Shows Arena SA",
    clientId: "client-24",
    value: 192000,
    monthlyValue: 16000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["bebidas", "eventos"],
    createdAt: d(2025, 12, 8),
    updatedAt: d(2025, 12, 22),
    expectedCloseDate: d(2025, 12, 26),
    status: "won",
    source: "Google Ads",
  },
  {
    id: "opp-w25",
    title: "Insumos - Catering Empresarial VIP",
    clientName: "Catering Empresarial VIP",
    clientId: "client-25",
    value: 144000,
    monthlyValue: 12000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["insumos", "catering"],
    createdAt: d(2025, 12, 10),
    updatedAt: d(2025, 12, 24),
    expectedCloseDate: d(2025, 12, 27),
    status: "won",
    source: "Indicacao",
  },
  {
    id: "opp-w26",
    title: "Congelados - Restaurante Mineiro Raiz",
    clientName: "Restaurante Mineiro Raiz ME",
    clientId: "client-26",
    value: 60000,
    monthlyValue: 5000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["congelados", "mineiro"],
    createdAt: d(2025, 12, 12),
    updatedAt: d(2025, 12, 26),
    expectedCloseDate: d(2025, 12, 28),
    status: "won",
    source: "Site",
  },
  {
    id: "opp-w27",
    title: "Carnes - Churrascaria Gaúcha Autêntica",
    clientName: "Churrascaria Gaúcha Autêntica Ltda",
    clientId: "client-27",
    value: 204000,
    monthlyValue: 17000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["carnes", "churrascaria"],
    createdAt: d(2025, 12, 15),
    updatedAt: d(2025, 12, 28),
    expectedCloseDate: d(2025, 12, 30),
    status: "won",
    source: "Indicacao",
  },
  // January 2026 (7 won)
  {
    id: "opp-w28",
    title: "Hortifruti - Restaurante Fazenda Velha",
    clientName: "Restaurante Fazenda Velha SA",
    clientId: "client-28",
    value: 168000,
    monthlyValue: 14000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["hortifruti", "fazenda"],
    createdAt: d(2026, 1, 2),
    updatedAt: d(2026, 1, 18),
    expectedCloseDate: d(2026, 1, 20),
    status: "won",
    source: "Feira Alimenta",
  },
  {
    id: "opp-w29",
    title: "Proteinas - Hotel Montanha Resort",
    clientName: "Hotel Montanha Resort SA",
    clientId: "client-29",
    value: 252000,
    monthlyValue: 21000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["proteinas", "hotel", "resort"],
    createdAt: d(2026, 1, 5),
    updatedAt: d(2026, 1, 20),
    expectedCloseDate: d(2026, 1, 23),
    status: "won",
    source: "LinkedIn",
  },
  {
    id: "opp-w30",
    title: "Embalagens - Rede Açaí Beach",
    clientName: "Rede Açaí Beach Ltda",
    clientId: "client-30",
    value: 48000,
    monthlyValue: 4000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["embalagens", "acai"],
    createdAt: d(2026, 1, 8),
    updatedAt: d(2026, 1, 22),
    expectedCloseDate: d(2026, 1, 25),
    status: "won",
    source: "Site",
  },
  {
    id: "opp-w31",
    title: "Bebidas - Cervejaria Artesanal Hop",
    clientName: "Cervejaria Artesanal Hop ME",
    clientId: "client-31",
    value: 84000,
    monthlyValue: 7000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["bebidas", "cervejaria"],
    createdAt: d(2026, 1, 10),
    updatedAt: d(2026, 1, 25),
    expectedCloseDate: d(2026, 1, 28),
    status: "won",
    source: "Indicacao",
  },
  {
    id: "opp-w32",
    title: "Laticinios - Cafeteria Grão Especial",
    clientName: "Cafeteria Grão Especial EIRELI",
    clientId: "client-32",
    value: 36000,
    monthlyValue: 3000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["laticinios", "cafeteria"],
    createdAt: d(2026, 1, 12),
    updatedAt: d(2026, 1, 27),
    expectedCloseDate: d(2026, 1, 29),
    status: "won",
    source: "Google Ads",
  },
  {
    id: "opp-w33",
    title: "Insumos - Restaurante Árabe Habibi",
    clientName: "Restaurante Árabe Habibi Ltda",
    clientId: "client-33",
    value: 96000,
    monthlyValue: 8000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["insumos", "arabe"],
    createdAt: d(2026, 1, 15),
    updatedAt: d(2026, 1, 28),
    expectedCloseDate: d(2026, 1, 30),
    status: "won",
    source: "Site",
  },
  {
    id: "opp-w34",
    title: "Congelados - Rede Tapioca Express",
    clientName: "Rede Tapioca Express ME",
    clientId: "client-34",
    value: 54000,
    monthlyValue: 4500,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["congelados", "tapioca"],
    createdAt: d(2026, 1, 18),
    updatedAt: d(2026, 1, 30),
    expectedCloseDate: d(2026, 1, 31),
    status: "won",
    source: "Indicacao",
  },
  // February 2026 (6 won so far)
  {
    id: "opp-w35",
    title: "Carnes premium - Restaurante Paris Bistro",
    clientName: "Restaurante Paris Bistro SA",
    clientId: "client-35",
    value: 228000,
    monthlyValue: 19000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["carnes", "frances", "premium"],
    createdAt: d(2026, 2, 1),
    updatedAt: d(2026, 2, 5),
    expectedCloseDate: d(2026, 2, 7),
    status: "won",
    source: "Feira Alimenta",
  },
  {
    id: "opp-w36",
    title: "Hortifruti - Spa Wellness Center",
    clientName: "Spa Wellness Center Ltda",
    value: 108000,
    monthlyValue: 9000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["hortifruti", "spa", "saudavel"],
    createdAt: d(2026, 2, 2),
    updatedAt: d(2026, 2, 6),
    expectedCloseDate: d(2026, 2, 8),
    status: "won",
    source: "LinkedIn",
  },
  {
    id: "opp-w37",
    title: "Proteinas - Restaurante Nordestino Sertão",
    clientName: "Restaurante Nordestino Sertão ME",
    value: 72000,
    monthlyValue: 6000,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["proteinas", "nordestino"],
    createdAt: d(2026, 2, 3),
    updatedAt: d(2026, 2, 7),
    expectedCloseDate: d(2026, 2, 8),
    status: "won",
    source: "Site",
  },
  {
    id: "opp-w38",
    title: "Bebidas - Pub Irlandês Dublin",
    clientName: "Pub Irlandês Dublin Ltda",
    value: 120000,
    monthlyValue: 10000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["bebidas", "pub"],
    createdAt: d(2026, 2, 4),
    updatedAt: d(2026, 2, 7),
    expectedCloseDate: d(2026, 2, 8),
    status: "won",
    source: "Indicacao",
  },
  {
    id: "opp-w39",
    title: "Embalagens - Dark Kitchen Central",
    clientName: "Dark Kitchen Central ME",
    value: 42000,
    monthlyValue: 3500,
    stage: "fechamento",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["embalagens", "darkkitchen"],
    createdAt: d(2026, 2, 5),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 8),
    status: "won",
    source: "Google Ads",
  },
  {
    id: "opp-w40",
    title: "Laticinios - Padaria Artesanal Fermento",
    clientName: "Padaria Artesanal Fermento EIRELI",
    value: 60000,
    monthlyValue: 5000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["laticinios", "padaria", "artesanal"],
    createdAt: d(2026, 2, 6),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 8),
    status: "won",
    source: "Site",
  },

  // === LOST OPPORTUNITIES (15) ===
  {
    id: "opp-l01",
    title: "Hortifruti - Restaurante Sol Nascente",
    clientName: "Restaurante Sol Nascente Ltda",
    value: 96000,
    monthlyValue: 8000,
    stage: "proposta-enviada",
    temperature: "cold",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["hortifruti"],
    createdAt: d(2025, 9, 10),
    updatedAt: d(2025, 10, 5),
    status: "lost",
    lossReason: "Preço",
    source: "Site",
    notes: "Optou por concorrente mais barato",
  },
  {
    id: "opp-l02",
    title: "Proteinas - Hotel Centro Executivo",
    clientName: "Hotel Centro Executivo SA",
    value: 144000,
    monthlyValue: 12000,
    stage: "negociacao",
    temperature: "warm",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["proteinas", "hotel"],
    createdAt: d(2025, 9, 15),
    updatedAt: d(2025, 10, 10),
    status: "lost",
    lossReason: "Prazo",
    source: "Indicacao",
    notes: "Não conseguimos atender prazo de entrega",
  },
  {
    id: "opp-l03",
    title: "Bebidas - Bar Universitário",
    clientName: "Bar Universitário ME",
    value: 36000,
    monthlyValue: 3000,
    stage: "contato-feito",
    temperature: "cold",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["bebidas"],
    createdAt: d(2025, 10, 1),
    updatedAt: d(2025, 10, 20),
    status: "lost",
    lossReason: "Sem retorno",
    source: "Google Ads",
  },
  {
    id: "opp-l04",
    title: "Carnes - Restaurante Tradicional",
    clientName: "Restaurante Tradicional Ltda",
    value: 180000,
    monthlyValue: 15000,
    stage: "proposta-enviada",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["carnes"],
    createdAt: d(2025, 10, 10),
    updatedAt: d(2025, 11, 5),
    status: "lost",
    lossReason: "Concorrência",
    source: "Feira Alimenta",
  },
  {
    id: "opp-l05",
    title: "Embalagens - Delivery Express Food",
    clientName: "Delivery Express Food ME",
    value: 24000,
    monthlyValue: 2000,
    stage: "reuniao-agendada",
    temperature: "cold",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["embalagens"],
    createdAt: d(2025, 10, 20),
    updatedAt: d(2025, 11, 10),
    status: "lost",
    lossReason: "Sem retorno",
    source: "Site",
  },
  {
    id: "opp-l06",
    title: "Laticinios - Sorveteria Tropical",
    clientName: "Sorveteria Tropical EIRELI",
    value: 48000,
    monthlyValue: 4000,
    stage: "negociacao",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["laticinios"],
    createdAt: d(2025, 11, 1),
    updatedAt: d(2025, 12, 1),
    status: "lost",
    lossReason: "Orçamento",
    source: "LinkedIn",
  },
  {
    id: "opp-l07",
    title: "Insumos - Cantina Empresa Tech",
    clientName: "Cantina Empresa Tech",
    value: 120000,
    monthlyValue: 10000,
    stage: "proposta-enviada",
    temperature: "cold",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["insumos", "corporativo"],
    createdAt: d(2025, 11, 10),
    updatedAt: d(2025, 12, 10),
    status: "lost",
    lossReason: "Projeto cancelado",
    source: "Licitacao",
  },
  {
    id: "opp-l08",
    title: "Congelados - Restaurante Família",
    clientName: "Restaurante Família ME",
    value: 60000,
    monthlyValue: 5000,
    stage: "contato-feito",
    temperature: "cold",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["congelados"],
    createdAt: d(2025, 11, 20),
    updatedAt: d(2025, 12, 15),
    status: "lost",
    lossReason: "Sem retorno",
    source: "Google Ads",
  },
  {
    id: "opp-l09",
    title: "Carnes - Hamburgueria Grill",
    clientName: "Hamburgueria Grill Ltda",
    value: 84000,
    monthlyValue: 7000,
    stage: "negociacao",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["carnes", "hamburgueria"],
    createdAt: d(2025, 12, 1),
    updatedAt: d(2026, 1, 5),
    status: "lost",
    lossReason: "Preço",
    source: "Indicacao",
  },
  {
    id: "opp-l10",
    title: "Bebidas - Danceteria Night",
    clientName: "Danceteria Night SA",
    value: 156000,
    monthlyValue: 13000,
    stage: "proposta-enviada",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["bebidas", "eventos"],
    createdAt: d(2025, 12, 10),
    updatedAt: d(2026, 1, 10),
    status: "lost",
    lossReason: "Concorrência",
    source: "Feira Alimenta",
  },
  {
    id: "opp-l11",
    title: "Hortifruti - Restaurante Diet Center",
    clientName: "Restaurante Diet Center ME",
    value: 72000,
    monthlyValue: 6000,
    stage: "reuniao-agendada",
    temperature: "cold",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["hortifruti", "dieta"],
    createdAt: d(2025, 12, 20),
    updatedAt: d(2026, 1, 15),
    status: "lost",
    lossReason: "Sem retorno",
    source: "Site",
  },
  {
    id: "opp-l12",
    title: "Proteinas - Restaurante Fitness",
    clientName: "Restaurante Fitness EIRELI",
    value: 96000,
    monthlyValue: 8000,
    stage: "negociacao",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["proteinas", "fitness"],
    createdAt: d(2026, 1, 5),
    updatedAt: d(2026, 1, 25),
    status: "lost",
    lossReason: "Orçamento",
    source: "LinkedIn",
  },
  {
    id: "opp-l13",
    title: "Embalagens - Marmitaria Popular",
    clientName: "Marmitaria Popular ME",
    value: 18000,
    monthlyValue: 1500,
    stage: "contato-feito",
    temperature: "cold",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["embalagens"],
    createdAt: d(2026, 1, 15),
    updatedAt: d(2026, 2, 1),
    status: "lost",
    lossReason: "Sem retorno",
    source: "Google Ads",
  },
  {
    id: "opp-l14",
    title: "Laticinios - Lanchonete Esquina",
    clientName: "Lanchonete Esquina ME",
    value: 30000,
    monthlyValue: 2500,
    stage: "proposta-enviada",
    temperature: "cold",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["laticinios"],
    createdAt: d(2026, 1, 20),
    updatedAt: d(2026, 2, 5),
    status: "lost",
    lossReason: "Preço",
    source: "Site",
  },
  {
    id: "opp-l15",
    title: "Insumos - Cantina Faculdade ABC",
    clientName: "Cantina Faculdade ABC",
    value: 84000,
    monthlyValue: 7000,
    stage: "negociacao",
    temperature: "warm",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["insumos", "faculdade"],
    createdAt: d(2026, 1, 25),
    updatedAt: d(2026, 2, 6),
    status: "lost",
    lossReason: "Licitação não ganha",
    source: "Licitacao",
  },

  // === OPEN OPPORTUNITIES (10) - Currently in pipeline ===
  {
    id: "opp-o01",
    title: "Carnes nobres - Restaurante Mediterrâneo",
    clientName: "Restaurante Mediterrâneo SA",
    value: 192000,
    monthlyValue: 16000,
    stage: "lead-in",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["carnes", "mediterraneo"],
    createdAt: d(2026, 2, 5),
    updatedAt: d(2026, 2, 6),
    expectedCloseDate: d(2026, 3, 15),
    status: "open",
    source: "Feira Alimenta",
    notes: "Primeiro contato na feira, muito interessado",
  },
  {
    id: "opp-o02",
    title: "Hortifruti premium - Hotel Fazenda Boa Vista",
    clientName: "Hotel Fazenda Boa Vista Ltda",
    value: 240000,
    monthlyValue: 20000,
    stage: "contato-feito",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["hortifruti", "hotel", "fazenda"],
    createdAt: d(2026, 2, 3),
    updatedAt: d(2026, 2, 7),
    expectedCloseDate: d(2026, 3, 10),
    status: "open",
    source: "LinkedIn",
    notes: "Reunião online agendada",
  },
  {
    id: "opp-o03",
    title: "Proteinas congeladas - Rede Restaurantes Executivos",
    clientName: "Rede Restaurantes Executivos SA",
    value: 360000,
    monthlyValue: 30000,
    stage: "reuniao-agendada",
    temperature: "hot",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["proteinas", "rede", "executivo"],
    createdAt: d(2026, 2, 1),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 3, 5),
    status: "open",
    source: "Indicacao",
    notes: "Grande oportunidade - 5 unidades",
  },
  {
    id: "opp-o04",
    title: "Bebidas importadas - Wine Bar Sommelier",
    clientName: "Wine Bar Sommelier EIRELI",
    value: 180000,
    monthlyValue: 15000,
    stage: "proposta-enviada",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["bebidas", "vinhos", "premium"],
    createdAt: d(2026, 1, 28),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 20),
    status: "open",
    source: "Site",
    notes: "Proposta entregue, aguardando retorno",
  },
  {
    id: "opp-o05",
    title: "Laticinios especiais - Rede Padarias Artesanais",
    clientName: "Rede Padarias Artesanais Ltda",
    value: 144000,
    monthlyValue: 12000,
    stage: "negociacao",
    temperature: "hot",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["laticinios", "padaria", "rede"],
    createdAt: d(2026, 1, 25),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 15),
    status: "open",
    source: "Google Ads",
    notes: "Negociando prazo de pagamento",
  },
  {
    id: "opp-o06",
    title: "Embalagens sustentáveis - Green Food Delivery",
    clientName: "Green Food Delivery ME",
    value: 60000,
    monthlyValue: 5000,
    stage: "fechamento",
    temperature: "hot",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["embalagens", "sustentavel", "delivery"],
    createdAt: d(2026, 1, 20),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 10),
    status: "open",
    source: "LinkedIn",
    notes: "Contrato em revisão jurídica",
  },
  {
    id: "opp-o07",
    title: "Insumos gerais - Hospital Regional Norte",
    clientName: "Hospital Regional Norte",
    value: 480000,
    monthlyValue: 40000,
    stage: "lead-in",
    temperature: "warm",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["insumos", "hospital", "licitacao"],
    createdAt: d(2026, 2, 6),
    updatedAt: d(2026, 2, 7),
    expectedCloseDate: d(2026, 4, 30),
    status: "open",
    source: "Licitacao",
    notes: "Preparando documentação para licitação",
  },
  {
    id: "opp-o08",
    title: "Congelados premium - Rede Pousadas Litoral Norte",
    clientName: "Rede Pousadas Litoral Norte SA",
    value: 216000,
    monthlyValue: 18000,
    stage: "contato-feito",
    temperature: "warm",
    responsibleId: "user-4",
    responsibleName: "Juliana Costa",
    tags: ["congelados", "pousada", "litoral"],
    createdAt: d(2026, 2, 4),
    updatedAt: d(2026, 2, 7),
    expectedCloseDate: d(2026, 3, 20),
    status: "open",
    source: "Feira Alimenta",
    notes: "Demanda alta na temporada de verão",
  },
  {
    id: "opp-o09",
    title: "Carnes - Restaurante Gaúcho Pampa",
    clientName: "Restaurante Gaúcho Pampa Ltda",
    value: 168000,
    monthlyValue: 14000,
    stage: "reuniao-agendada",
    temperature: "hot",
    responsibleId: "user-6",
    responsibleName: "Marcos Pereira",
    tags: ["carnes", "gaucho"],
    createdAt: d(2026, 2, 2),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 28),
    status: "open",
    source: "Indicacao",
    notes: "Reunião presencial marcada para amanhã",
  },
  {
    id: "opp-o10",
    title: "Bebidas - Beach Club Maré Alta",
    clientName: "Beach Club Maré Alta SA",
    value: 300000,
    monthlyValue: 25000,
    stage: "proposta-enviada",
    temperature: "hot",
    responsibleId: "user-3",
    responsibleName: "Lucas Oliveira",
    tags: ["bebidas", "beach", "premium"],
    createdAt: d(2026, 1, 30),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 25),
    status: "open",
    source: "Google Ads",
    notes: "Proposta competitiva enviada",
  },
  // === OPEN OPPORTUNITIES (user-1) - Created for testing Pipeline ===
  {
    id: "opp-u1-01",
    title: "Vinhos Importados - Restaurante La Bella",
    clientName: "Restaurante La Bella Ltda",
    value: 85000,
    monthlyValue: 7000,
    stage: "lead-in",
    temperature: "hot",
    responsibleId: "user-1",
    responsibleName: "Rafael Mendes",
    tags: ["vinhos", "italiano"],
    createdAt: d(2026, 2, 8),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 3, 1),
    status: "open",
    source: "Indicacao",
    notes: "Interesse em carta de vinhos exclusivos",
  },
  {
    id: "opp-u1-02",
    title: "Cervejas Artesanais - Bar do Léo",
    clientName: "Bar do Léo ME",
    value: 45000,
    monthlyValue: 3500,
    stage: "contato-feito",
    temperature: "warm",
    responsibleId: "user-1",
    responsibleName: "Rafael Mendes",
    tags: ["cerveja", "bar"],
    createdAt: d(2026, 2, 7),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 3, 5),
    status: "open",
    source: "Site",
    notes: "Agendar visita para degustação",
  },
  {
    id: "opp-u1-03",
    title: "Insumos - Padaria Pão Dourado",
    clientName: "Padaria Pão Dourado EIRELI",
    value: 120000,
    monthlyValue: 10000,
    stage: "reuniao-agendada",
    temperature: "hot",
    responsibleId: "user-1",
    responsibleName: "Rafael Mendes",
    tags: ["padaria", "insumos"],
    createdAt: d(2026, 2, 5),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 28),
    status: "open",
    source: "Google Ads",
    notes: "Reunião para apresentar catálogo de farinhas",
  },
  {
    id: "opp-u1-04",
    title: "Carnes Premium - Churrascaria Boi Preto",
    clientName: "Churrascaria Boi Preto SA",
    value: 350000,
    monthlyValue: 30000,
    stage: "proposta-enviada",
    temperature: "hot",
    responsibleId: "user-1",
    responsibleName: "Rafael Mendes",
    tags: ["churrascaria", "carnes"],
    createdAt: d(2026, 2, 1),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 20),
    status: "open",
    source: "Feira Alimenta",
    notes: "Aguardando aprovação da diretoria",
  },
  {
    id: "opp-u1-05",
    title: "Hortifruti - Rede de Hotéis Sol",
    clientName: "Rede de Hotéis Sol SA",
    value: 500000,
    monthlyValue: 40000,
    stage: "negociacao",
    temperature: "hot",
    responsibleId: "user-1",
    responsibleName: "Rafael Mendes",
    tags: ["hotel", "rede", "hortifruti"],
    createdAt: d(2026, 1, 20),
    updatedAt: d(2026, 2, 8),
    expectedCloseDate: d(2026, 2, 15),
    status: "open",
    source: "Linkedin",
    notes: "Negociando contrato global para a rede",
  },
];
