import type { TeamUser } from "@/types";

// ===== Mock Users =====

export const mockUsers: TeamUser[] = [
  {
    id: "user-1",
    name: "Rafael Mendes",
    email: "rafael.mendes@flow.com.br",
    role: "master",
    isActive: true,
    phone: "(11) 99876-5432",
    unitId: "unit-1",
    unitName: "Matriz - Sao Paulo",
    createdAt: "2025-06-10",
    lastLogin: "2026-02-08",
  },
  {
    id: "user-2",
    name: "Camila Ferreira",
    email: "camila.ferreira@flow.com.br",
    role: "admin",
    isActive: true,
    phone: "(11) 98765-4321",
    unitId: "unit-1",
    unitName: "Matriz - Sao Paulo",
    createdAt: "2025-07-05",
    lastLogin: "2026-02-08",
  },
  {
    id: "user-3",
    name: "Lucas Oliveira",
    email: "lucas.oliveira@flow.com.br",
    role: "comercial",
    isActive: true,
    phone: "(21) 99654-3210",
    unitId: "unit-2",
    unitName: "Filial - Rio de Janeiro",
    createdAt: "2025-08-12",
    lastLogin: "2026-02-08",
  },
  {
    id: "user-4",
    name: "Juliana Costa",
    email: "juliana.costa@flow.com.br",
    role: "comercial",
    isActive: true,
    phone: "(11) 97654-3210",
    unitId: "unit-1",
    unitName: "Matriz - Sao Paulo",
    createdAt: "2025-08-20",
    lastLogin: "2026-02-07",
  },
  {
    id: "user-5",
    name: "Fernanda Lima",
    email: "fernanda.lima@flow.com.br",
    role: "cs",
    isActive: true,
    phone: "(11) 96543-2109",
    unitId: "unit-1",
    unitName: "Matriz - Sao Paulo",
    createdAt: "2025-09-08",
    lastLogin: "2026-02-08",
  },
  {
    id: "user-6",
    name: "Marcos Pereira",
    email: "marcos.pereira@flow.com.br",
    role: "comercial",
    isActive: true,
    phone: "(31) 95432-1098",
    unitId: "unit-3",
    unitName: "Filial - Belo Horizonte",
    createdAt: "2025-09-15",
    lastLogin: "2026-02-06",
  },
  {
    id: "user-7",
    name: "Carolina Santos",
    email: "carolina.santos@flow.com.br",
    role: "cs",
    isActive: true,
    phone: "(11) 94321-0987",
    unitId: "unit-1",
    unitName: "Matriz - Sao Paulo",
    createdAt: "2025-10-01",
    lastLogin: "2026-02-08",
  },
  {
    id: "user-8",
    name: "Pedro Almeida",
    email: "pedro.almeida@flow.com.br",
    role: "leitura",
    isActive: true,
    phone: "(21) 93210-9876",
    unitId: "unit-2",
    unitName: "Filial - Rio de Janeiro",
    createdAt: "2025-11-10",
    lastLogin: "2026-02-05",
  },
];
