import type { Visit } from "@/types";
import { daysAgo, daysFromNow } from "./helpers";

// ===== Mock Visits (25 visits across opportunities) =====

export const mockVisits: Visit[] = [
  // opp-o01 — Carnes nobres - Restaurante Fazenda Velha
  {
    id: "visit-1",
    opportunityId: "opp-o01",
    clientId: "client-28",
    type: "presencial",
    location: "Restaurante Fazenda Velha - Campinas",
    status: "realizada",
    startAt: daysAgo(14),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Apresentar cardápio de carnes e coletar requisitos.",
    result: "Cliente aprovou a linha premium. Solicita proposta formal.",
    outcome: "realizada",
    durationMinutes: 90,
    createdAt: daysAgo(16),
  },
  {
    id: "visit-2",
    opportunityId: "opp-o01",
    clientId: "client-28",
    type: "presencial",
    location: "Restaurante Fazenda Velha - Campinas",
    status: "agendada",
    startAt: daysFromNow(3),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Fechar condições finais de contrato.",
    durationMinutes: 60,
    createdAt: daysAgo(2),
  },

  // opp-o02 — Hortifruti completo - Hotel Montanha Resort
  {
    id: "visit-3",
    opportunityId: "opp-o02",
    clientId: "client-29",
    type: "presencial",
    location: "Hotel Montanha Resort - Petrópolis",
    status: "realizada",
    startAt: daysAgo(21),
    responsible: "Juliana Costa",
    responsibleId: "user-4",
    objective: "Visita técnica à cozinha do hotel.",
    result: "Levantamento completo das necessidades. Volume alto.",
    outcome: "realizada",
    durationMinutes: 120,
    createdAt: daysAgo(23),
  },
  {
    id: "visit-4",
    opportunityId: "opp-o02",
    clientId: "client-29",
    type: "remoto",
    location: "Google Meet",
    status: "realizada",
    startAt: daysAgo(10),
    responsible: "Juliana Costa",
    responsibleId: "user-4",
    objective: "Alinhar contraproposta e volumes.",
    result: "Hotel aceita negociar setup. Pedir aprovação interna.",
    outcome: "realizada",
    durationMinutes: 45,
    platform: "google-meet",
    link: "https://meet.google.com/abc-hotel",
    createdAt: daysAgo(12),
  },

  // opp-o03 — Açaí e polpas - Rede Açaí Beach
  {
    id: "visit-5",
    opportunityId: "opp-o03",
    clientId: "client-30",
    type: "presencial",
    location: "Rede Açaí Beach - Barra da Tijuca",
    status: "realizada",
    startAt: daysAgo(8),
    responsible: "Marcos Pereira",
    responsibleId: "user-6",
    objective: "Degustação de polpas premium.",
    result: "Aprovaram 3 dos 5 sabores. Pedir amostras extras.",
    outcome: "realizada",
    durationMinutes: 60,
    createdAt: daysAgo(10),
  },
  {
    id: "visit-6",
    opportunityId: "opp-o03",
    clientId: "client-30",
    type: "presencial",
    location: "Rede Açaí Beach - Copacabana",
    status: "agendada",
    startAt: daysFromNow(5),
    responsible: "Marcos Pereira",
    responsibleId: "user-6",
    objective: "Apresentar proposta comercial formal.",
    durationMinutes: 45,
    createdAt: daysAgo(1),
  },

  // opp-o04 — Insumos cervejeiros - Cervejaria Artesanal Hop
  {
    id: "visit-7",
    opportunityId: "opp-o04",
    clientId: "client-31",
    type: "presencial",
    location: "Cervejaria Artesanal Hop - Pinheiros",
    status: "realizada",
    startAt: daysAgo(6),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Conhecer operação e entender demanda de insumos.",
    result: "Boa receptividade. Querem catálogo completo de lúpulos.",
    outcome: "realizada",
    durationMinutes: 75,
    createdAt: daysAgo(8),
  },

  // opp-o05 — Laticínios especiais - Rede Padarias Artesanais
  {
    id: "visit-8",
    opportunityId: "opp-o05",
    clientId: "client-32",
    type: "remoto",
    location: "Zoom",
    status: "realizada",
    startAt: daysAgo(19),
    responsible: "Juliana Costa",
    responsibleId: "user-4",
    objective: "Apresentar linha de laticínios importados.",
    result: "Interesse alto. Quer amostras para teste.",
    outcome: "realizada",
    durationMinutes: 40,
    platform: "zoom",
    link: "https://zoom.us/j/padaria",
    createdAt: daysAgo(21),
  },
  {
    id: "visit-9",
    opportunityId: "opp-o05",
    clientId: "client-32",
    type: "presencial",
    location: "Cafeteria Grão Especial - Vila Madalena",
    status: "realizada",
    startAt: daysAgo(11),
    responsible: "Juliana Costa",
    responsibleId: "user-4",
    objective: "Entrega de amostras e degustação.",
    result: "Aprovaram queijos. Manteiga precisa ajuste no mix.",
    outcome: "realizada",
    durationMinutes: 50,
    createdAt: daysAgo(13),
  },

  // opp-o06 — Embalagens sustentáveis - Green Food Delivery
  {
    id: "visit-10",
    opportunityId: "opp-o06",
    clientId: "client-33",
    type: "presencial",
    location: "Restaurante Árabe Habibi - Moema",
    status: "realizada",
    startAt: daysAgo(28),
    responsible: "Marcos Pereira",
    responsibleId: "user-6",
    objective: "Levantar tipos de embalagem necessários.",
    result: "Mapeamento completo. 8 SKUs diferentes.",
    outcome: "realizada",
    durationMinutes: 60,
    createdAt: daysAgo(30),
  },
  {
    id: "visit-11",
    opportunityId: "opp-o06",
    clientId: "client-33",
    type: "remoto",
    location: "WhatsApp Vídeo",
    status: "realizada",
    startAt: daysAgo(4),
    responsible: "Marcos Pereira",
    responsibleId: "user-6",
    objective: "Alinhamento final antes do acordo.",
    result: "Acordo verbal fechado. Formalizar contrato.",
    outcome: "realizada",
    durationMinutes: 30,
    platform: "whatsapp",
    createdAt: daysAgo(5),
  },

  // opp-o07 — Insumos gerais - Hospital Regional Norte
  {
    id: "visit-12",
    opportunityId: "opp-o07",
    clientId: "client-16",
    type: "presencial",
    location: "Hospital Santa Cruz - Centro",
    status: "realizada",
    startAt: daysAgo(4),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Reunião com equipe de compras do hospital.",
    result: "Entregamos documentação para licitação.",
    outcome: "realizada",
    durationMinutes: 90,
    createdAt: daysAgo(6),
  },
  {
    id: "visit-13",
    opportunityId: "opp-o07",
    clientId: "client-16",
    type: "presencial",
    location: "Hospital Santa Cruz - Centro",
    status: "agendada",
    startAt: daysFromNow(7),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Apresentar amostras de produtos ao comitê técnico.",
    durationMinutes: 120,
    createdAt: daysAgo(1),
  },

  // opp-o08 — Proteínas - Steakhouse Premium
  {
    id: "visit-14",
    opportunityId: "opp-o08",
    clientId: "client-20",
    type: "presencial",
    location: "Steakhouse Premium - Itaim Bibi",
    status: "realizada",
    startAt: daysAgo(11),
    responsible: "Juliana Costa",
    responsibleId: "user-4",
    objective: "Degustação de cortes premium com chef.",
    result: "Chef aprovou wagyu e angus. Descartou cordeiro.",
    outcome: "realizada",
    durationMinutes: 90,
    createdAt: daysAgo(13),
  },

  // opp-o09 — Resort all-inclusive - Resort Praia Azul
  {
    id: "visit-15",
    opportunityId: "opp-o09",
    clientId: "client-21",
    type: "presencial",
    location: "Resort Praia Azul - Guarujá",
    status: "realizada",
    startAt: daysAgo(5),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Visita técnica a cozinha e almoxarifado do resort.",
    result: "Operação complexa com 3 restaurantes internos. Alto volume.",
    outcome: "realizada",
    durationMinutes: 180,
    createdAt: daysAgo(7),
  },
  {
    id: "visit-16",
    opportunityId: "opp-o09",
    clientId: "client-21",
    type: "remoto",
    location: "Google Meet",
    status: "agendada",
    startAt: daysFromNow(4),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Alinhamento de proposta com diretoria.",
    durationMinutes: 60,
    platform: "google-meet",
    link: "https://meet.google.com/resort-azul",
    createdAt: daysAgo(1),
  },

  // opp-o10 — Eventos - Casa de Shows Arena
  {
    id: "visit-17",
    opportunityId: "opp-o10",
    clientId: "client-24",
    type: "presencial",
    location: "Casa de Shows Arena - Vila Olímpia",
    status: "realizada",
    startAt: daysAgo(16),
    responsible: "Marcos Pereira",
    responsibleId: "user-6",
    objective: "Entender operação de catering para eventos.",
    result: "Modelo de fornecimento por evento. Mapeamos 4 tipos.",
    outcome: "realizada",
    durationMinutes: 90,
    createdAt: daysAgo(18),
  },
  {
    id: "visit-18",
    opportunityId: "opp-o10",
    clientId: "client-24",
    type: "presencial",
    location: "Casa de Shows Arena - Vila Olímpia",
    status: "cancelada",
    startAt: daysAgo(9),
    responsible: "Marcos Pereira",
    responsibleId: "user-6",
    objective: "Apresentar proposta revisada.",
    cancellationReason: "Evento de última hora no local. Remarcado.",
    outcome: "remarcada",
    durationMinutes: 60,
    createdAt: daysAgo(11),
  },
  {
    id: "visit-19",
    opportunityId: "opp-o10",
    clientId: "client-24",
    type: "presencial",
    location: "Casa de Shows Arena - Vila Olímpia",
    status: "agendada",
    startAt: daysFromNow(2),
    responsible: "Marcos Pereira",
    responsibleId: "user-6",
    objective: "Apresentar proposta revisada (remarcado).",
    durationMinutes: 60,
    createdAt: daysAgo(3),
  },

  // Visitas em oportunidades won para timeline de clientes
  {
    id: "visit-20",
    opportunityId: "opp-w35",
    clientId: "client-35",
    type: "presencial",
    location: "Restaurante Paris Bistro - Jardins",
    status: "realizada",
    startAt: daysAgo(25),
    responsible: "Juliana Costa",
    responsibleId: "user-4",
    objective: "Fechamento do contrato de carnes premium.",
    result: "Contrato assinado. Início da operação em 15 dias.",
    outcome: "realizada",
    durationMinutes: 60,
    createdAt: daysAgo(27),
  },
  {
    id: "visit-21",
    opportunityId: "opp-w01",
    clientId: "client-1",
    type: "presencial",
    location: "Restaurante Sabor da Terra - Centro",
    status: "realizada",
    startAt: daysAgo(150),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Apresentação inicial do portfólio de hortifruti.",
    result: "Muito receptivos. Agendaram segunda visita.",
    outcome: "realizada",
    durationMinutes: 75,
    createdAt: daysAgo(152),
  },
  {
    id: "visit-22",
    opportunityId: "opp-w02",
    clientId: "client-2",
    type: "presencial",
    location: "Hotel Beira Mar - Copacabana",
    status: "realizada",
    startAt: daysAgo(145),
    responsible: "Juliana Costa",
    responsibleId: "user-4",
    objective: "Visita à cozinha central do hotel.",
    result: "Mapeamento de necessidades completo.",
    outcome: "realizada",
    durationMinutes: 120,
    createdAt: daysAgo(147),
  },
  {
    id: "visit-23",
    opportunityId: "opp-w07",
    clientId: "client-7",
    type: "presencial",
    location: "Churrascaria Fogo Alto - Moema",
    status: "realizada",
    startAt: daysAgo(120),
    responsible: "Lucas Oliveira",
    responsibleId: "user-3",
    objective: "Degustação de cortes com o chef.",
    result: "Chef aprovou todos os cortes. Fechamento em 1 semana.",
    outcome: "realizada",
    durationMinutes: 90,
    createdAt: daysAgo(122),
  },
  {
    id: "visit-24",
    opportunityId: "opp-w10",
    clientId: "client-10",
    type: "remoto",
    location: "Zoom",
    status: "realizada",
    startAt: daysAgo(100),
    responsible: "Marcos Pereira",
    responsibleId: "user-6",
    objective: "Apresentar proposta para rede de pousadas.",
    result: "Aprovado pelo conselho. Contrato em processo.",
    outcome: "realizada",
    durationMinutes: 60,
    platform: "zoom",
    link: "https://zoom.us/j/pousadas",
    createdAt: daysAgo(102),
  },
];
